name: Node.js CI
run-name: ${{ github.actor }} is Node.js

on:
  push:
    branches:
        - main
        - build
  pull_request:
    branches:
        - main
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
           node-version: '20'
           cache: 'npm'
       - run: npm install
       - run: npm test
       - run: npm run build --if-present

