name: Node.js CI
run-name: ${{ github.actor }} is Node.js

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g pnpm
      - run: npm install --save-dev jest
      - run: echo "Tests to be added"
      - run: npm run build --if-present
      - run: npm publish
